name: PlayerPromote
version: '0.1.4'
main: com.jaytak.playerPromote.PlayerPromote
api-version: '1.21'
commands:
  agree:
    description: Promotes the player to the "player" group.
    usage: /agree
    permission: playerpromote.use